apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3 # Run 3 instances of our app for availability.
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # IMPORTANT: We will replace this image placeholder in our CI/CD pipeline.
        image: YOUR_ECR_REGISTRY/multi-cloud-auditor/backend:latest
        ports:
        - containerPort: 5000 