apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    # This selector ensures the service directs traffic to pods with the 'app: backend' label.
    app: backend
  ports:
    - protocol: TCP
      port: 80 # The port the service will expose.
      targetPort: 5000 # The port on the pod to forward traffic to.
  # Type ClusterIP means this service is only reachable from within the cluster.
  type: ClusterIP